package com.ratelimiter.marketing.config;

import com.zaxxer.hikari.HikariDataSource;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;

/**
 * Read-only access to {@code marketing_agency.db} generated by {@code dataset.py}.
 * Primary {@code spring.datasource} remains {@code rate_limiter.db} for JPA.
 */
@Configuration
public class MarketingDataSourceConfig {

    public static final String MARKETING_JDBC = "marketingJdbcTemplate";

    @Bean(name = "marketingDataSource")
    public DataSource marketingDataSource() {
        HikariDataSource ds = new HikariDataSource();
        ds.setJdbcUrl("jdbc:sqlite:./marketing_agency.db");
        ds.setDriverClassName(org.sqlite.JDBC.class.getName());
        ds.setMaximumPoolSize(2);
        ds.setPoolName("marketing-pool");
        return ds;
    }

    @Bean(name = MARKETING_JDBC)
    public JdbcTemplate marketingJdbcTemplate(@Qualifier("marketingDataSource") DataSource dataSource) {
        return new JdbcTemplate(dataSource);
    }
}
